# Generated by Django 3.2 on 2021-04-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Coin Name')),
                ('ticker', models.CharField(max_length=20, verbose_name='Coin Alias')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Coin Address')),
            ],
        ),
    ]
